"""Behavior tests for the trusted post-publication state machine."""

import importlib.util
import base64
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts/symphony"
sys.path.insert(0, str(SCRIPTS))
SPEC = importlib.util.spec_from_file_location("review", SCRIPTS / "review.py")
review = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(review)


def pr(sha="a" * 40, state="open", head="symphony/issue-28", fork=False):
    return {"number": 99, "state": state, "merged": False, "body": "Refs #28",
            "base": {"ref": "main", "sha": "d" * 40,
                     "repo": {"full_name": review.REPO}},
            "head": {"ref": head, "sha": sha,
                     "repo": {"full_name": "someone/fork" if fork else review.REPO}}}


class ValidationTests(unittest.TestCase):
    LOCK = '''# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fixture"
version = "0.1.0"
dependencies = [
 "libc",
]

[[package]]
name = "libc"
version = "0.2.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
'''
    MANIFEST = '''[package]
name = "fixture"
version = "0.1.0"

[dependencies]
'''

    def test_accepts_only_the_expected_open_same_repository_pr_and_sha(self):
        with patch.object(review, "one", return_value=pr()):
            self.assertEqual(review.expected_pr(28, 99, "a" * 40)["head"]["sha"], "a" * 40)
        for value in (pr(state="closed"), pr(head="other"), pr(fork=True), pr("b" * 40)):
            with self.subTest(value=value), patch.object(review, "one", return_value=value):
                with self.assertRaises(review.ReviewStopped):
                    review.expected_pr(28, 99, "a" * 40)

    def test_required_checks_fail_closed_when_missing_or_failed(self):
        success = {"id": 1, "name": "Linux", "status": "completed", "conclusion": "success"}
        with patch.dict(os.environ, {"SYMPHONY_REQUIRED_CHECKS": "Linux,macOS"}), \
                patch.object(review, "one", return_value={"check_runs": [success]}):
            self.assertEqual(review.check_state("a" * 40)[0], "pending")
        failed = {"id": 2, "name": "macOS", "status": "completed", "conclusion": "failure",
                  "output": {"title": "test failed", "summary": "bounded diagnostic"}}
        with patch.dict(os.environ, {"SYMPHONY_REQUIRED_CHECKS": "Linux,macOS"}), \
                patch.object(review, "one", return_value={"check_runs": [success, failed]}):
            state, failures, _ = review.check_state("a" * 40)
            self.assertEqual(state, "failed")
            self.assertEqual(review.failed_logs(failures)[0]["check"], "macOS")
        for value in ("", ",,", "Linux,Linux"):
            with self.subTest(value=value), patch.dict(
                    os.environ, {"SYMPHONY_REQUIRED_CHECKS": value}), \
                    patch.object(review, "one", return_value={"check_runs": [success]}):
                with self.assertRaises(review.ReviewStopped):
                    review.check_state("a" * 40)

    def test_existing_locked_dependency_addition_is_low_risk(self):
        files = {("Cargo.lock", "base"): self.LOCK,
                 ("Cargo.lock", "head"): self.LOCK,
                 ("Cargo.toml", "base"): self.MANIFEST,
                 ("Cargo.toml", "head"): self.MANIFEST + 'libc = "0.2"\n'}
        with patch.object(review, "repository_file", side_effect=lambda path, sha: files[path, sha]):
            self.assertIsNone(review.cargo_risk("base", "head", {"Cargo.toml"}))

    def test_lock_package_identity_changes_are_high_risk(self):
        changes = {
            "new": self.LOCK + '\n[[package]]\nname = "new"\nversion = "1.0.0"\n',
            "removed": self.LOCK.split("[[package]]\nname = \"libc\"")[0],
            "version": self.LOCK.replace('version = "0.2.1"', 'version = "0.2.2"'),
            "source": self.LOCK.replace("crates.io-index", "example.invalid/index"),
            "checksum": self.LOCK.replace('checksum = "abc"', 'checksum = "def"'),
        }
        for kind, head in changes.items():
            with self.subTest(kind=kind), patch.object(
                    review, "repository_file",
                    side_effect=lambda path, sha, changed=head: self.LOCK if sha == "base" else changed):
                self.assertEqual(review.cargo_risk("base", "head", {"Cargo.lock"}),
                                 "Cargo.lock package identities changed")

    def test_lock_dependency_graph_changes_are_high_risk(self):
        head = self.LOCK.replace(' "libc",', ' "libc 0.2.1",')
        with patch.object(
                review, "repository_file",
                side_effect=lambda path, sha: self.LOCK if sha == "base" else head):
            self.assertEqual(review.cargo_risk("base", "head", {"Cargo.lock"}),
                             "Cargo.lock dependency graph changed")

    def test_lock_dependency_order_is_normalized(self):
        base = self.LOCK.replace(' "libc",', ' "libc",\n "second",')
        head = self.LOCK.replace(' "libc",', ' "second",\n "libc",')
        with patch.object(
                review, "repository_file",
                side_effect=lambda path, sha: base if sha == "base" else head):
            self.assertIsNone(review.cargo_risk("base", "head", {"Cargo.lock"}))

    def test_manifest_non_dependency_or_complex_dependency_changes_are_high_risk(self):
        heads = {
            "feature": self.MANIFEST + '[features]\ndefault = []\n',
            "source": self.MANIFEST + 'libc = { version = "0.2", registry = "private" }\n',
            "git": self.MANIFEST + 'libc = { git = "https://example.invalid/repo" }\n',
            "path": self.MANIFEST + 'libc = { path = "vendor/libc" }\n',
            "profile": self.MANIFEST + '[profile.release]\nlto = true\n',
            "build": self.MANIFEST.replace('[package]\n', '[package]\nbuild = "build.rs"\n'),
            "changed": self.MANIFEST.replace('version = "0.1.0"', 'version = "0.2.0"'),
        }
        for kind, head in heads.items():
            files = {("Cargo.lock", "base"): self.LOCK, ("Cargo.lock", "head"): self.LOCK,
                     ("Cargo.toml", "base"): self.MANIFEST, ("Cargo.toml", "head"): head}
            with self.subTest(kind=kind), patch.object(
                    review, "repository_file", side_effect=lambda path, sha: files[path, sha]):
                self.assertEqual(review.cargo_risk("base", "head", {"Cargo.toml"}),
                                 "Cargo.toml changed outside simple dependency additions")

    def test_missing_invalid_and_oversized_cargo_files_fail_closed(self):
        valid = b"version = 4\n"
        response = {"type": "file", "name": "Cargo.lock", "path": "Cargo.lock",
                    "encoding": "base64", "size": len(valid), "sha": "a" * 40,
                    "content": base64.b64encode(valid).decode()}
        with patch.object(review, "one", return_value=response):
            self.assertEqual(review.repository_file("Cargo.lock", "a" * 40), valid.decode())
        for change in ({"size": 0}, {"size": review.MAX_CARGO_FILE_BYTES + 1},
                       {"encoding": "none"}, {"content": "not base64!"}, {"path": "other"}):
            invalid = dict(response, **change)
            with self.subTest(change=change), patch.object(review, "one", return_value=invalid):
                with self.assertRaises(review.ReviewStopped):
                    review.repository_file("Cargo.lock", "a" * 40)
        with patch.object(review, "one", side_effect=review.ReviewStopped("missing")):
            with self.assertRaises(review.ReviewStopped):
                review.repository_file("Cargo.lock", "a" * 40)

    def test_invalid_or_ambiguous_lock_is_rejected(self):
        invalid = ("", "version = 4\n[[package]]\nname = \"x\"\n",
                   self.LOCK.replace('checksum = "abc"', 'checksum = "abc"\nchecksum = "def"'),
                   self.LOCK.replace("dependencies = [\n \"libc\",\n]", "dependencies = [\n bad\n]"),
                   self.LOCK.replace(' "libc",', ' "libc",\n "libc",'))
        for document in invalid:
            with self.subTest(document=document):
                with self.assertRaises(review.ReviewStopped):
                    review.lock_packages(document)

    def test_existing_policy_boundaries_still_stop(self):
        cases = (([{"filename": "docs/architecture.md", "patch": ""}],
                  "architecture-boundary files changed"),
                 ([{"filename": "src/ipc/message.rs", "patch": ""}],
                  "storage, IPC, authentication, or process-policy files changed"),
                 ([{"filename": "src/main.rs",
                    "patch": "+ StrictHostKeyChecking=no"}],
                  "high-risk policy or destructive behavior detected"))
        for files, reason in cases:
            with self.subTest(reason=reason), patch.object(review, "listing", return_value=files):
                self.assertEqual(review.risk_reason(99, "a" * 40, "b" * 40), reason)

    def test_context_rejects_credentials_before_codex(self):
        context = {"review": "github_pat_" + "x" * 30}
        with patch("subprocess.run") as run:
            with self.assertRaises(review.ReviewStopped):
                review.remediation(ROOT, context)
            run.assert_not_called()

    def test_remediation_pins_gpt_6_sol_and_strips_remote_credentials(self):
        completed = __import__("subprocess").CompletedProcess([], 0)
        with tempfile.TemporaryDirectory() as directory, \
                patch.dict(os.environ, {"SYMPHONY_GITHUB_TOKEN": "secret",
                                        "GH_TOKEN": "secret", "SSH_AUTH_SOCK": "/agent",
                                        "GIT_DIR": "/agent/repository"}), \
                patch("subprocess.run", return_value=completed) as run:
            review.remediation(Path(directory), {"kind": "untrusted_diagnostics"})
        command = run.call_args.args[0]
        child_env = run.call_args.kwargs["env"]
        self.assertEqual(command[:4], ["codex", "exec", "-c", 'model=gpt-6-sol'])
        for key in ("SYMPHONY_GITHUB_TOKEN", "GH_TOKEN", "GITHUB_TOKEN", "SSH_AUTH_SOCK",
                    "GIT_DIR"):
            self.assertNotIn(key, child_env)

    def test_push_uses_trusted_noninteractive_askpass(self):
        def completed(command, **_kwargs):
            output = ""
            if command[-2:] in (["rev-parse", "HEAD"], ["rev-parse", "FETCH_HEAD"]):
                output = "b" * 40 + "\n"
            elif command[1:3] == ["bundle", "list-heads"]:
                output = "b" * 40 + " HEAD\n"
            return __import__("subprocess").CompletedProcess(command, 0, stdout=output)

        with patch.dict(os.environ, {"SYMPHONY_CONTROL_ROOT": str(ROOT),
                                    "SYMPHONY_STATE_ROOT": str(ROOT),
                                    "SYMPHONY_GITHUB_TOKEN": "secret"}), \
                patch("subprocess.run", side_effect=completed) as run:
            review.push(ROOT, 28, "b" * 40, "a" * 40)
        command = run.call_args.args[0]
        self.assertEqual(command[0], "git")
        self.assertNotIn("setpriv", command)
        self.assertEqual(command[-3:], [
            "--force-with-lease=refs/heads/symphony/issue-28:" + "a" * 40,
            f"https://github.com/{review.REPO}.git",
            "b" * 40 + ":refs/heads/symphony/issue-28"])
        self.assertIn("core.hooksPath=/dev/null", command)
        self.assertIn("credential.helper=", command)
        push_env = run.call_args.kwargs["env"]
        self.assertEqual(push_env["GIT_TERMINAL_PROMPT"], "0")
        self.assertEqual(push_env["GIT_ASKPASS"],
                         str(ROOT / "scripts/symphony/git-askpass.sh"))
        commands = [call.args[0] for call in run.call_args_list]
        bundle_command = next(command for command in commands if "bundle" in command)
        self.assertEqual(bundle_command[-4:], ["bundle", "create", "-", "HEAD"])
        fetch_command = next(command for command in commands if "fetch" in command)
        self.assertTrue(fetch_command[-2].endswith("/source.bundle"))
        self.assertNotEqual(fetch_command[-2], str(ROOT))

    def test_root_push_bundles_workspace_as_agent(self):
        def completed(command, **_kwargs):
            output = ""
            if command[-2:] in (["rev-parse", "HEAD"], ["rev-parse", "FETCH_HEAD"]):
                output = "b" * 40 + "\n"
            elif command[1:3] == ["bundle", "list-heads"]:
                output = "b" * 40 + " HEAD\n"
            return __import__("subprocess").CompletedProcess(command, 0, stdout=output)

        with patch.object(review.os, "geteuid", return_value=0), \
                patch.dict(os.environ, {"SYMPHONY_CONTROL_ROOT": str(ROOT),
                                        "SYMPHONY_STATE_ROOT": str(ROOT),
                                        "SYMPHONY_GITHUB_TOKEN": "secret",
                                        "SYMPHONY_AGENT_UID": "1234",
                                        "SYMPHONY_AGENT_GID": "5678"}), \
                patch("subprocess.run", side_effect=completed) as run:
            review.push(ROOT, 28, "b" * 40, "a" * 40)
        commands = [call.args[0] for call in run.call_args_list]
        bundle_command = next(command for command in commands if "bundle" in command)
        self.assertEqual(bundle_command[:4], ["setpriv", "--reuid=1234",
                         "--regid=5678", "--clear-groups"])
        self.assertEqual(bundle_command[-4:], ["bundle", "create", "-", "HEAD"])

    def test_bundle_creation_uses_exportable_head_and_contains_exact_commit(self):
        with tempfile.TemporaryDirectory() as directory:
            repository = Path(directory) / "repository"
            bundle = Path(directory) / "source.bundle"
            env = review.credential_free_env()
            subprocess.run(["git", "init", "-q", str(repository)], check=True, env=env)
            subprocess.run(["git", "-C", str(repository), "config", "user.name", "Fixture"],
                           check=True, env=env)
            subprocess.run(["git", "-C", str(repository), "config", "user.email",
                            "fixture@example.invalid"], check=True, env=env)
            (repository / "fixture").write_text("content\n", encoding="utf-8")
            subprocess.run(["git", "-C", str(repository), "add", "fixture"],
                           check=True, env=env)
            subprocess.run(["git", "-C", str(repository), "commit", "-q", "-m", "fixture"],
                           check=True, env=env)
            commit = subprocess.run(["git", "-C", str(repository), "rev-parse", "HEAD"],
                                    check=True, env=env, text=True,
                                    stdout=subprocess.PIPE).stdout.strip()

            review.create_bundle(repository, commit, bundle)

            heads = subprocess.run(["git", "bundle", "list-heads", str(bundle)], check=True,
                                   env=env, text=True,
                                   stdout=subprocess.PIPE).stdout.splitlines()
            self.assertIn(f"{commit} HEAD", heads)

    def test_bundle_creation_rejects_an_advertised_head_mismatch(self):
        completed = __import__("subprocess").CompletedProcess

        def run(command, **_kwargs):
            if command[-2:] == ["rev-parse", "HEAD"]:
                return completed(command, 0, stdout="b" * 40 + "\n")
            if command[1:3] == ["bundle", "list-heads"]:
                return completed(command, 0, stdout="c" * 40 + " HEAD\n")
            return completed(command, 0, stdout="")

        with tempfile.TemporaryDirectory() as directory, \
                patch("subprocess.run", side_effect=run):
            with self.assertRaisesRegex(review.ReviewStopped, "bundle HEAD"):
                review.create_bundle(ROOT, "b" * 40, Path(directory) / "source.bundle")

    def test_root_review_drops_to_the_configured_workspace_owner(self):
        with patch("os.geteuid", return_value=0), \
                patch.dict(os.environ, {"SYMPHONY_AGENT_UID": "1234",
                                        "SYMPHONY_AGENT_GID": "5678"}):
            self.assertEqual(review.agent_prefix(), ["setpriv", "--reuid=1234",
                             "--regid=5678", "--clear-groups"])
        with patch("os.geteuid", return_value=0), patch.dict(os.environ, {}, clear=True):
            with self.assertRaises(review.ReviewStopped):
                review.agent_prefix()

    def test_unresolved_coderabbit_line_comment_keeps_location_and_sha(self):
        response = {"data": {"repository": {"pullRequest": {"reviewThreads": {
            "pageInfo": {"hasNextPage": False}, "nodes": [{"isResolved": False,
                "comments": {"pageInfo": {"hasNextPage": False}, "nodes": [{
                    "body": "actionable finding", "path": "src/lib.rs", "line": 7,
                    "commit": {"oid": "a" * 40}, "author": {"login": "coderabbitai[bot]"}}]}}]}}}}}
        completed = __import__("subprocess").CompletedProcess([], 0, json.dumps(response), "")
        with patch.dict(os.environ, {"SYMPHONY_GITHUB_TOKEN": "test-token"}), \
                patch("subprocess.run", return_value=completed), \
                patch.object(review, "api", return_value=[[]]):
            self.assertEqual(review.review_findings(99, "a" * 40), [{
                "body": "actionable finding", "path": "src/lib.rs", "line": 7,
                "commit_sha": "a" * 40}])

    def test_current_head_actionable_review_body_is_a_finding(self):
        response = {"data": {"repository": {"pullRequest": {"reviewThreads": {
            "pageInfo": {"hasNextPage": False}, "nodes": []}}}}}
        completed = __import__("subprocess").CompletedProcess([], 0, json.dumps(response), "")
        reviews = [[{"id": 7, "body": "**Actionable comments posted: 2**",
                    "commit_id": "a" * 40, "user": {"login": "coderabbitai"}}]]
        with patch.dict(os.environ, {"SYMPHONY_GITHUB_TOKEN": "test-token"}), \
                patch("subprocess.run", return_value=completed), \
                patch.object(review, "api", return_value=reviews):
            findings = review.review_findings(99, "a" * 40)
        self.assertEqual(findings[0]["source"], "review_body")

    def test_failure_fingerprint_ignores_head_and_finding_commit(self):
        first = {"head_sha": "a" * 40, "failed_checks": [{"check": "Linux"}],
                 "review_findings": [{"body": "same", "commit_sha": "a" * 40}]}
        second = {"head_sha": "b" * 40, "failed_checks": [{"check": "Linux"}],
                  "review_findings": [{"body": "same", "commit_sha": "b" * 40}]}
        self.assertEqual(review.fingerprint(first), review.fingerprint(second))


class StateMachineTests(unittest.TestCase):
    def base_patches(self):
        return (patch.object(review, "expected_pr", return_value=pr()),
                patch.object(review, "open_dependencies", return_value=[]),
                patch.object(review, "risk_reason", return_value=None),
                patch.object(review, "review_findings", return_value=[]),
                patch.object(review, "review_state", return_value=(Path("state"), {
                    "issue": 28, "pull_request": 99, "started": __import__("time").time(),
                    "attempts": 0, "fingerprint": None})))

    def test_clean_success_revalidates_and_merges_exact_sha_then_closes(self):
        merged = dict(pr(state="closed"), merged=True, merge_commit_sha="c" * 40)
        calls = []

        def fake_api(endpoint, method="GET", body=None):
            calls.append((endpoint, method, body))

        p1, p2, p3, p4, p5 = self.base_patches()
        with p1, p2, p3, p4, p5, patch.object(review, "check_state", return_value=("success", [], [])), \
                patch.object(review, "api", side_effect=fake_api), \
                patch.object(review, "one", return_value=merged), patch.object(review, "record"):
            self.assertEqual(review.run(ROOT, 28, 99), "c" * 40)
        merge = next(call for call in calls if call[0].endswith("/merge"))
        self.assertEqual(merge[2], {"merge_method": "squash", "sha": "a" * 40})
        self.assertIn((f"repos/{review.REPO}/issues/28", "PATCH", {"state": "closed"}), calls)

    def test_new_dependency_during_final_revalidation_never_merges(self):
        p1, _, p3, p4, p5 = self.base_patches()
        with p1, p3, p4, p5, patch.object(review, "check_state", return_value=("success", [], [])), \
                patch.object(review, "open_dependencies", side_effect=[[], [26]]), \
                patch.object(review, "transition_issue", side_effect=review.ReviewStopped("dependency")), \
                patch.object(review, "api") as api:
            with self.assertRaises(review.ReviewStopped):
                review.run(ROOT, 28, 99)
            self.assertFalse(any(call.args[0].endswith("/merge") for call in api.call_args_list))

    def test_repeated_failure_stops_without_second_remediation(self):
        failed = [{"name": "Linux", "output": {"summary": "same"}}]
        p1, p2, p3, p4, p5 = self.base_patches()
        with p1, p2, p3, p4, p5, patch.object(review, "check_state", return_value=("failed", failed, [])), \
                patch.object(review, "git", side_effect=["a" * 40, "symphony/issue-28",
                                                         "b" * 40, "", "b" * 40, "",
                                                         "fixture change"]), \
                patch.object(review, "remediation") as remediate, \
                patch.object(review, "local_verify"), patch("subprocess.run"), \
                patch.object(review, "push"), \
                patch.object(review, "record"), patch.object(review, "save_state"), \
                patch.object(review, "transition_issue", side_effect=review.ReviewStopped("repeat")):
            with self.assertRaisesRegex(review.ReviewStopped, "repeat"):
                review.run(ROOT, 28, 99)
            self.assertEqual(remediate.call_count, 1)

    def test_attempt_is_persisted_before_remediation_push(self):
        failed = [{"name": "Linux", "output": {"summary": "new failure"}}]
        order = []
        p1, p2, p3, p4, p5 = self.base_patches()
        with p1, p2, p3, p4, p5, \
                patch.object(review, "check_state", return_value=("failed", failed, [])), \
                patch.object(review, "git", side_effect=["a" * 40, "symphony/issue-28",
                                                         "b" * 40, "", "b" * 40, "",
                                                         "fixture change"]), \
                patch.object(review, "remediation"), patch.object(review, "local_verify"), \
                patch.object(review, "save_state",
                             side_effect=lambda _path, state: order.append(
                                 ("save", state["attempts"], state["fingerprint"]))), \
                patch.object(review, "push",
                             side_effect=lambda *_args: (_ for _ in ()).throw(
                                 review.ReviewStopped("push failed"))):
            with self.assertRaisesRegex(review.ReviewStopped, "push failed"):
                review.run(ROOT, 28, 99)
        self.assertEqual(order[0][0:2], ("save", 1))
        self.assertRegex(order[0][2], r"^[0-9a-f]{64}$")


if __name__ == "__main__":
    unittest.main()
